### PR TITLE
Implement no_std support

### PR DESCRIPTION
**Pull request by vks**
* Unfortunately, some functionality from `core` had to be vendored, because it is not exposed by stable Rust. Hopefully this functionality will be in the `num_traits` crate version 0.2. This would allow deleting the newly added traits.
* The code taken from Rust is MPL/Apache licensed. I think the BSD license is more permissive? I would suggest to relicense this crate under MPL/Apache, to reduce friction with the Rust ecosystem. Alternatively, the `BasicFloat` could be implemented in a separate crate with a separate license, or we just wait until its functionality is provided by `num_traits`.

### CODE REVIEW

**Comment by Eh2406** [comment]
Thank you so much! This is a really good improvement! Are you using my project for something!?

The code is BSD because it is derived from previous work that is BSD. If I re-license under MPL/Apache do I need to get permission from the persons I derived it from?

Does this compile on rust 1.0.0? If not what is the oldest version this works on? I rashly decided in my readme that changing minimum rust version is a breaking change. Which may be worth doing, but does require some care.

**Comment by vks** [comment]
> Are you using my project for something!?

Not yet, but I might in the future. :) I want to have some way to do numerical integration on crates.io, so I'm interested in your crate. (I'll probably work on bindings or a port for [cuba](http://www.feynarts.de/cuba/) to have something for multidimensional integration.)

> The code is BSD because it is derived from previous work that is BSD. If I re-license under MPL/Apache do I need to get permission from the persons I derived it from?

I'm not so sure myself. [This blog post](https://blog.gerv.net/2013/02/relicensing-when-do-you-have-to-ask/) seems to suggest that it is possible to relicense BSD code as MPL/Apache (but not the other way around).

> Does this compile on rust 1.0.0? If not what is the oldest version this works on? I rashly decided in my readme that changing minimum rust version is a breaking change. Which may be worth doing, but does require some care.

Unfortunately not, the minimum version required by num-traits is 1.8. I'll see whether I can get rid of the dependency.

**Comment by vks** [comment]
Removing the `num_traits` dependency gives me problems with `f64::ln`. It cannot be easily accessed with `no_std` on stable. :(

**Comment by Eh2406** [comment]
So I have re-licensed the project.
I'd love to see/help with a multivariable integration library. I'd prefer a port rather then bindings just for the ease of installation/bare_matal/wasm support. It should probably have good integration with ndarray. 

Overall this looks go to me. The nits left:

- bump the min rust test in both CI
- bump the min rust in the readme
- update the change log to show the no_std in an unreleased breaking change
- set up some kind of reminder for when num_traits 0.2 is released

**Comment by vks** [comment]
See https://github.com/rust-num/num-traits/pull/32 for the related PR.

**Comment by Eh2406** [comment]
Looks good so far, appveyor needs to be updated then I am good to merge.

**Comment by Eh2406** [comment]
Thank you again!

**Pull request merged**
